#!/bin/sh -e

# Input files (.in)
INPUT_FILES=$(ls files/*.in --format=single-column)
OUTPUT_FILES=$(ls files/*.out --format=single-column)
IFS=$'\r\n' GLOBIGNORE='*' command eval 'INPUT_FILES=($INPUT_FILES)'
IFS=$'\r\n' GLOBIGNORE='*' command eval 'OUTPUT_FILES=($OUTPUT_FILES)'

# Colors
BLACK='\e[0;30m';       B_BLACK='\e[1;30m';
RED='\e[0;31m';         B_RED='\e[1;31m';
GREEN='\e[0;32m';       B_GREEN="\e[1;32m"
YELLOW='\e[0;33m';      B_YELLOW='\e[1;33m';
BLUE='\e[0;34m';        B_BLUE='\e[1;34m';
PURPLE='\e[0;35m';      B_PURPLE='\e[1;35m';
CYAN='\e[0;36m';        B_CYAN='\e[1;36m';
WHITE='\e[0;37m';       B_WHITE='\e[1;37m';

HEAD_INPUT="${WHITE} [  Input   ]"
HEAD_RUN="${GREEN} [   Run    ]"
HEAD_BAD_RUN="${RED} [   Run    ]"
HEAD_RESULT="${GREEN} [  Result  ]"
HEAD_BAD_RESULT="${RED} [  Result  ]"
HEAD_EXPECTED="${WHITE} [ Expected ]"
HEAD_OUTPUT="${RED} [  Output  ]"

echo -e "${WHITE}----------------------------------------------------------"
echo -e "                    Lukasiewicz Tests                     "
echo -e "----------------------------------------------------------"
echo -e "${WHITE} Input Files Directory (.in): ${B_WHITE}files/ ${B_BLUE}(${#INPUT_FILES[@]} files)"
echo -e "${WHITE} Output Files Directory (.out): ${B_WHITE}files/ ${B_BLUE}(${#OUTPUT_FILES[@]} files)"
echo -e "${WHITE}----------------------------------------------------------"

# For every input file found in files/
for i in "${INPUT_FILES[@]}"
do
    echo -e "$HEAD_INPUT $i"
    # Get the expected output file name (.out)
    OUTPUT_FILE="${i%.*}".out

    # If output file exists, then runs the test
    if [[ -f $OUTPUT_FILE ]]
    then
        echo -e "$HEAD_RUN Expected output file: $OUTPUT_FILE"
        
        # Runs the test and stores the output
        OUTPUT="$(../lukasiewicz < $i)"
        EXPECTED_OUTPUT="$(cat $OUTPUT_FILE)"
        
        if [ "$EXPECTED_OUTPUT" = "$OUTPUT" ]; then 
            echo -e "$HEAD_RESULT Success!"
            echo "True"
        else
            echo -e "$HEAD_BAD_RESULT Failed!"
            #echo -e "$HEAD_EXPECTED"
            #echo -e "$EXPECTED_OUTPUT\n"
            #echo -e "$HEAD_OUTPUT"
            #echo -e "$OUTPUT\n"
        fi

    else
        echo -e "$HEAD_BAD_RUN No output file $OUTPUT_FILE was found!"
    fi
    
done

exit 0
